### ISSUE TITLE
Asked to get output at node 1, but the layer has only 1 inbound nodes.

### ISSUE THREAD

**Issue by elyselam** [EvilPort2/PhotoStylist#1]
I get this message after python3 photo_stylist.py and chose the pictures I wanted. Thanks.

Total params: 14,714,688
Trainable params: 14,714,688
Non-trainable params: 0
_________________________________________________________________
Traceback (most recent call last):
  File "photo_stylist.py", line 29, in <module>
    content_model = Model(vgg.input, vgg.layers[conv_layers[7]].get_output_at(1))
  File "/anaconda3/lib/python3.6/site-packages/keras/engine/base_layer.py", line 741, in get_output_at
    'output')
  File "/anaconda3/lib/python3.6/site-packages/keras/engine/base_layer.py", line 670, in _get_node_attribute_at_index
    str(len(self._inbound_nodes)) + ' inbound nodes.')
ValueError: Asked to get output at node 1, but the layer has only 1 inbound nodes.

**Comment by EvilPort2** [comment]
Not sure why this happened.

**Comment by EvilPort2** [comment]
ok. The error is fixed now. It was happening as I was using an older version of Keras and Tensorflow and you were using the new one. Download the repo again.
